### ISSUE TITLE
Torque lint errors in V8

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/node-v8#110] opened 2019-06-15 02:30 UTC
Hi @hashseed! We've been hitting some snags while fixing canary with the new versions of V8 (7.7.x). Precisely, we have linting errors in the torque code. I have no clue how it could have passed the V8 CI?

```
../../deps/v8/src/builtins/array.tq:35:3: Lint error: Macro 'IsJSArray' is never used.
../../deps/v8/src/builtins/base.tq:398:1: Lint error: Macro 'NewJSArray' is never used.
../../deps/v8/src/builtins/base.tq:382:3: Lint error: Macro 'IsEmpty' is never used.
```

**Comment by hashseed** [comment] 2019-06-15 07:13
@szuend

**Comment by szuend** [comment] 2019-06-15 11:51
This is weird. I remember removing some of these upstream while landing the CL that produces lint errors for unused macros.

Macros marked as unused can safely be removed from the code, *with one exception*: Macros _only_ used in asserts are wrongly reported as unused in release builds. As a workaround, such macros can be marked with `@export`.

**Comment by targos** [comment] 2019-06-17 06:24
The problem is that those three things are only used in `test/torque/test-torque.tq` which we don't build in Node.
Also `IsEmpty()` cannot be marked with `@export` because it's a method, not a macro.

**Comment by targos** [comment] 2019-06-17 07:29
Adding `test/torque/test-torque.tq` to `v8.gyp` seems to be enough. I'm building with it...

**Comment by targos** [comment] 2019-06-17 07:56
That did the trick

**Closed by targos** 2019-06-17 07:56 UTC
