### ISSUE TITLE
debug build is broken

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/node-v8#145] opened 2020-02-28 03:38 UTC
```console
#
# Fatal error in ../../deps/v8/src/codegen/x64/assembler-x64.h, line 123
# Debug check failed: SmiValuesAre31Bits().
#
#
#
#FailureMessage Object: 0x7ffd71883620
==== C stack trace ===============================

    ../../out/Debug/mksnapshot(v8::base::debug::StackTrace::StackTrace()+0x12) [0x556454ba4262]
    ../../out/Debug/mksnapshot(+0x1276cda) [0x556453e01cda]
    ../../out/Debug/mksnapshot(V8_Fatal(char const*, int, char const*, ...)+0x17b) [0x556453df7d9b]
    ../../out/Debug/mksnapshot(+0x126cdcb) [0x556453df7dcb]
    ../../out/Debug/mksnapshot(v8::internal::Builtins::Generate_InterpreterEntryTrampoline(v8::internal::MacroAssembler*)+0xaa2) [0x5564548e1ae2]
    ../../out/Debug/mksnapshot(+0x1838c0e) [0x5564543c3c0e]
    ../../out/Debug/mksnapshot(v8::internal::SetupIsolateDelegate::SetupBuiltinsInternal(v8::internal::Isolate*)+0x996) [0x5564543c4bb6]
    ../../out/Debug/mksnapshot(v8::internal::SetupIsolateDelegate::SetupBuiltins(v8::internal::Isolate*)+0x58) [0x556453dee968]
    ../../out/Debug/mksnapshot(v8::internal::Isolate::Init(v8::internal::ReadOnlyDeserializer*, v8::internal::StartupDeserializer*)+0x1166) [0x5564533e77a6]
    ../../out/Debug/mksnapshot(v8::SnapshotCreator::SnapshotCreator(v8::Isolate*, long const*, v8::StartupData*)+0xfd) [0x55645326cfdd]
    ../../out/Debug/mksnapshot(v8::internal::CreateSnapshotDataBlobInternal(v8::SnapshotCreator::FunctionCodeHandling, char const*, v8::Isolate*)+0x4d) [0x5564538f3b6d]
    ../../out/Debug/mksnapshot(main+0x2bc) [0x556453255afc]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f3b78f701e3]
    ../../out/Debug/mksnapshot(_start+0x2e) [0x5564532613ce]
Illegal instruction (core dumped)
ninja: build stopped: subcommand failed.
```

**Comment by addaleax** [comment] 2020-02-28 03:40
Duplicate of https://github.com/nodejs/node-v8/issues/140

**Closed by addaleax** 2020-02-28 03:40 UTC

**Comment by gengjiawen** [comment] 2020-02-28 06:17
Sorry missing this part :(
