### ISSUE TITLE
Most recently published v8 canary builds don't have files for most systems

### ISSUE THREAD

**Issue by nolanmar511** [nodejs/node-v8#131] opened 2019-12-06 19:33 UTC
I absolutely love being able use the V8 canary builds!
The most recently published builds are giving me some issues, though.

When I try to install the latest V8 canary build, I get a 404 error:
```
NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary nvm install node
Downloading and installing node v14.0.0-v8-canary2019120581584c67f0...
Downloading https://nodejs.org/download/v8-canary/v14.0.0-v8-canary2019120581584c67f0/node-v14.0.0-v8-canary2019120581584c67f0-linux-x64.tar.xz...
curl: (22) The requested URL returned error: 404 
```

When I visit  https://nodejs.org/download/v8-canary/v14.0.0-v8-canary2019120581584c67f0/ only a few of the usual builds are listed:
```
../
SHASUMS256.txt                                     05-Dec-2019 10:55                 380
node-v14.0.0-v8-canary2019120581584c67f0-aix-pp..> 05-Dec-2019 10:51            41211103
node-v14.0.0-v8-canary2019120581584c67f0-linux-..> 05-Dec-2019 10:19            32297480
node-v14.0.0-v8-canary2019120581584c67f0-linux-..> 05-Dec-2019 10:20            20151780
```

I assume this is related to the recent build failures.

**Comment by addaleax** [comment] 2019-12-06 19:37
Yeah, I could imagine this is related to the https://github.com/nodejs/node-v8/issues/127 failures … I think the builds here come from our release CI to which I don’t have access to, but maybe @targos could confirm that that’s the cause?

**Comment by targos** [comment] 2019-12-06 23:10
Yes, in particular, the Linux build fails because of https://github.com/nodejs/node-v8/issues/130

**Comment by targos** [comment] 2019-12-09 09:47
There are now files for Linux and macOS

**Comment by targos** [comment] 2020-01-13 13:12
I'm closing this as a duplicate of https://github.com/nodejs/node-v8/issues/127.

**Closed by targos** 2020-01-13 13:12 UTC
